update

diff --git a/.github/workflows/run_musicas_recentes.yml b/.github/workflows/run_musicas_recentes.yml
--- a/.github/workflows/run_musicas_recentes.yml
+++ b/.github/workflows/run_musicas_recentes.yml
@@ -40,13 +40,27 @@ jobs:
       run: |
         poetry run python musicas_recentes_actions.py
     
-    - name: Commit and push changes
+    - name: Verify if CSV was created
       working-directory: ./src/assets
       run: |
-        git config --local user.name "github-actions[bot]"
-        git config --local user.email "github-actions[bot]@users.noreply.github.com"
-        git add ../../musicas_ouvidas.csv
-        git commit -m "Update musicas_ouvidas.csv"
-        git push
+        if [ -f "musicas_ouvidas.csv" ]; then
+          echo "CSV file exists."
+        else
+          echo "CSV file does not exist."
+          exit 1
+        fi
+
+    - name: Commit and push changes if CSV exists
+      working-directory: ./src/assets
+      run: |
+        if [ -f "musicas_ouvidas.csv" ]; then
+          git config --local user.name "github-actions[bot]"
+          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+          git add musicas_ouvidas.csv
+          git commit -m "Update musicas_ouvidas.csv"
+          git push
+        else
+          echo "CSV file not found, skipping commit."
+        fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
